# Generated by Django 3.2.9 on 2021-11-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_produto_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='consumo_medio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
