# Generated by Django 3.2.9 on 2021-11-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_remove_produto_peso_caixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque_maximo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_minimo',
            field=models.IntegerField(default=0),
        ),
    ]
