# Generated by Django 3.2.9 on 2021-11-21 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_auto_20211117_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='data',
            new_name='data_entrada',
        ),
        migrations.RenameField(
            model_name='saida',
            old_name='data',
            new_name='data_saida',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='fornecedor',
        ),
        migrations.AddField(
            model_name='entrada',
            name='fornecedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estoque.fornecedor'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
